# Generated by Django 5.0.7 on 2025-08-27 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=120)),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("industry", models.CharField(blank=True, max_length=120)),
                ("values", models.TextField(blank=True)),
                ("style_keywords", models.CharField(blank=True, max_length=200)),
                ("colors", models.CharField(blank=True, max_length=200)),
                ("icon_ideas", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogoConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("source", models.CharField(default="openai", max_length=20)),
                ("preview_png", models.ImageField(upload_to="logos/previews/")),
                ("svg_file", models.FileField(blank=True, upload_to="logos/svg/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concepts",
                        to="logo_generator.logoproject",
                    ),
                ),
            ],
        ),
    ]
