# Generated by Django 5.0.7 on 2025-08-26 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NameIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        help_text="Comma-separated keywords", max_length=200
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=120)),
                (
                    "style",
                    models.CharField(
                        blank=True, help_text="e.g., modern, playful", max_length=80
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        help_text="One or more suggested names (newline separated)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
