# Generated by Django 5.0.7 on 2025-08-30 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("name_generator", "0001_initial"),
    ]

    operations = []
