"""Email delivery for competitor intelligence reports."""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dataclasses import dataclass

from dotenv import load_dotenv

load_dotenv()


@dataclass
class EmailConfig:
    """Email configuration from environment variables."""

    smtp_host: str
    smtp_port: int
    smtp_user: str
    smtp_password: str
    from_email: str
    to_email: str

    @classmethod
    def from_env(cls) -> "EmailConfig":
        """Load email config from environment."""
        return cls(
            smtp_host=os.getenv("SMTP_HOST", "smtp.gmail.com"),
            smtp_port=int(os.getenv("SMTP_PORT", "587")),
            smtp_user=os.getenv("SMTP_USER", ""),
            smtp_password=os.getenv("SMTP_PASSWORD", ""),
            from_email=os.getenv("EMAIL_FROM", ""),
            to_email=os.getenv("EMAIL_TO", ""),
        )

    def is_configured(self) -> bool:
        """Check if email is properly configured."""
        return all([
            self.smtp_host,
            self.smtp_user,
            self.smtp_password,
            self.from_email,
            self.to_email,
        ])


def send_report_email(
    report: str,
    subject: str | None = None,
    to_email: str | None = None,
) -> bool:
    """Send a competitor intelligence report via email.

    Args:
        report: The markdown report content
        subject: Email subject (default: auto-generated with date)
        to_email: Recipient email (default: from EMAIL_TO env var)

    Returns:
        True if email sent successfully, False otherwise

    Raises:
        ValueError: If email is not configured
    """
    config = EmailConfig.from_env()

    if not config.is_configured():
        raise ValueError(
            "Email not configured. Set these environment variables:\n"
            "  SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, EMAIL_FROM, EMAIL_TO"
        )

    recipient = to_email or config.to_email
    today = datetime.now().strftime("%Y-%m-%d")

    if subject is None:
        subject = f"Webnode Competitor Intelligence Report - {today}"

    # Create message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.from_email
    msg["To"] = recipient

    # Plain text version
    text_content = f"""Webnode Weekly Competitive Intelligence Report
Generated: {today}

{report}

---
This report was automatically generated by the Webnode Competitive Intelligence System.
"""

    # HTML version (basic markdown-like formatting)
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }}
        h2 {{ color: #1e40af; margin-top: 30px; }}
        h3 {{ color: #3b82f6; }}
        ul {{ padding-left: 20px; }}
        li {{ margin: 8px 0; }}
        .meta {{ color: #6b7280; font-size: 14px; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; }}
        strong {{ color: #1f2937; }}
        code {{ background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }}
    </style>
</head>
<body>
    <h1>Webnode Competitor Intelligence Report</h1>
    <p class="meta">Generated: {today}</p>

    <div class="content">
        {_markdown_to_html(report)}
    </div>

    <div class="footer">
        <p>This report was automatically generated by the Webnode Competitive Intelligence System.</p>
    </div>
</body>
</html>
"""

    msg.attach(MIMEText(text_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))

    # Send email
    try:
        with smtplib.SMTP(config.smtp_host, config.smtp_port) as server:
            server.starttls()
            server.login(config.smtp_user, config.smtp_password)
            server.send_message(msg)
        return True
    except Exception as e:
        raise RuntimeError(f"Failed to send email: {e}")


def _markdown_to_html(text: str) -> str:
    """Basic markdown to HTML conversion."""
    import re

    # Headers
    text = re.sub(r"^### (.+)$", r"<h3>\1</h3>", text, flags=re.MULTILINE)
    text = re.sub(r"^## (.+)$", r"<h2>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^# (.+)$", r"<h1>\1</h1>", text, flags=re.MULTILINE)

    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)

    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)

    # Bullet points
    text = re.sub(r"^- (.+)$", r"<li>\1</li>", text, flags=re.MULTILINE)
    text = re.sub(r"(<li>.*</li>\n?)+", r"<ul>\g<0></ul>", text)

    # Line breaks
    text = re.sub(r"\n\n", "</p><p>", text)
    text = f"<p>{text}</p>"

    # Clean up empty paragraphs
    text = re.sub(r"<p>\s*</p>", "", text)
    text = re.sub(r"<p>\s*(<[hul])", r"\1", text)
    text = re.sub(r"(</[hul][^>]*>)\s*</p>", r"\1", text)

    return text
